name: Deploy API to Azure Web App

on:
  push:
    branches:
      - master
    paths:
      - 'src/api/**'
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore src/api/api.csproj

    - name: Build
      run: dotnet build src/api/api.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish src/api/api.csproj --configuration Release --no-build --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'app-202509dotnetlab-api'  # Replace with your Azure Web App name
        package: ./publish