name: Deploy Front to Azure Web App

on:
  push:
    branches:
      - master
    paths:
      - 'src/front/**'
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: src/front/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: src/front

    - name: Build
      run: npm run build
      working-directory: src/front

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'app-dotnetlab-202509'  # Replace with your Azure Web App name
        package: src/front/dist/front/browser